package io.testproject.completetestform;

import io.testproject.java.annotations.v2.Parameter;
import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.ParameterDirection;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.WebDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.WebTest;
import io.testproject.java.sdk.v2.tests.helpers.WebTestHelper;
import java.lang.String;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: TestProject Tutorial
 * Test: Login Test
 * Generated by: Rex Jones II (Rex.Jones@Test4Success.org)
 * Generated on Wed Jul 08 01:03:29 GMT 2020.
 */
@Test(
    name = "Login Test",
    description = "Log Into TestProject Example Page",
    version = "1.0"
)
public class LoginTest implements WebTest {
  @Parameter(
      description = "Auto generated application URL parameter",
      defaultValue = "https://example.testproject.io/web/",
      direction = ParameterDirection.INPUT
  )
  public String ApplicationURL;

  public ExecutionResult execute(WebTestHelper helper) throws FailureException {
    WebDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    boolean booleanResult;
    String string;

    // 1. Navigate to '{{ApplicationURL}}'
    //    Navigates the specified URL (Auto-generated)
    booleanResult = driver.testproject().navigateToUrl(ApplicationURL);
    report.step(String.format("Navigate to '%s'",ApplicationURL), booleanResult, TakeScreenshotConditionType.Never);

    // 2. Click 'name'
    by = By.cssSelector("#name");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'name'", booleanResult, TakeScreenshotConditionType.Never);

    // 3. Type 'Rex Jones II' in 'name'
    by = By.cssSelector("#name");
    booleanResult = driver.testproject().typeText(by,"Rex Jones II");
    report.step("Type 'Rex Jones II' in 'name'", booleanResult, TakeScreenshotConditionType.Never);

    // 4. Type '12345' in 'password'
    by = By.cssSelector("#password");
    booleanResult = driver.testproject().typeText(by,"12345");
    report.step("Type '12345' in 'password'", booleanResult, TakeScreenshotConditionType.Never);

    // 5. Click 'login'
    by = By.cssSelector("#login");
    booleanResult = driver.testproject().click(by);
    report.step("Click 'login'", booleanResult, TakeScreenshotConditionType.Never);

    // 6. Get text from 'greetings'
    //    Get Greeting Message
    by = By.cssSelector("#greetings");
    string = driver.testproject().getText(by);
    report.step("Get text from 'greetings'", string != null && string.contains("Rex Jones II"), TakeScreenshotConditionType.Always);

    return ExecutionResult.PASSED;
  }
}
