package io.testproject.completetestform;

import io.testproject.java.enums.AutomatedBrowserType;
import io.testproject.java.execution.results.StepExecutionResult;
import io.testproject.java.sdk.v2.Runner;
import java.lang.Exception;
import java.lang.String;

/**
 * This class was automatically generated by TestProject
 * Provides an example how to run coded TestProject tests
 */
public class TestprojectTutorialRunner {
  public static String developerToken = "qZsMILMrKduKIu7vuE_UZKCPH07Kj5sCqRE8qEoXEBE1";

  public static AutomatedBrowserType browserType = AutomatedBrowserType.Chrome;

  public static void main(String[] args) {
    try {
      runCompleteTestForm();
    }
    catch (Exception e) {
    }
  }

  /**
   * Runs "CompleteTestForm"
   */
  public static StepExecutionResult runCompleteTestForm() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new CompleteTestForm(), true);
  }

  /**
   * Runs "LoginTest"
   */
  public static StepExecutionResult runLoginTest() throws Exception {
    Runner runner = Runner.createWeb(developerToken,browserType);
    return runner.run(new LoginTest(), true);
  }
}
